'use server';

/**
 * @fileOverview Optimizes a coding-related prompt using AI.
 *
 * - optimizeCodePrompt - A function that optimizes a code prompt.
 * - OptimizeCodePromptInput - The input type for the optimizeCodePrompt function.
 * - OptimizeCodePromptOutput - The return type for the optimizeCodePrompt function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const OptimizeCodePromptInputSchema = z.object({
  originalPrompt: z
    .string()
    .describe('The original coding-related prompt to be optimized.'),
});
export type OptimizeCodePromptInput = z.infer<typeof OptimizeCodePromptInputSchema>;

const OptimizeCodePromptOutputSchema = z.object({
  optimizedPrompt: z
    .string()
    .describe('The optimized coding-related prompt generated by AI.'),
});
export type OptimizeCodePromptOutput = z.infer<typeof OptimizeCodePromptOutputSchema>;

export async function optimizeCodePrompt(input: OptimizeCodePromptInput): Promise<OptimizeCodePromptOutput> {
  return optimizeCodePromptFlow(input);
}

const prompt = ai.definePrompt({
  name: 'optimizeCodePromptPrompt',
  input: {
    schema: z.object({
      originalPrompt: z
        .string()
        .describe('The original coding-related prompt to be optimized.'),
    }),
  },
  output: {
    schema: z.object({
      optimizedPrompt: z
        .string()
        .describe('The optimized coding-related prompt generated by AI.'),
    }),
  },
  prompt: `You are an AI expert in prompt engineering, specializing in optimizing prompts for code generation.

  Your goal is to refine the given prompt to elicit higher-quality and more relevant code generation from language models.
  Consider factors such as clarity, specificity, and the inclusion of relevant context or constraints.

  Original Prompt: {{{originalPrompt}}}

  Optimized Prompt:`, // Removed 'Here' since it's not natural language
});

const optimizeCodePromptFlow = ai.defineFlow<
  typeof OptimizeCodePromptInputSchema,
  typeof OptimizeCodePromptOutputSchema
>(
  {
    name: 'optimizeCodePromptFlow',
    inputSchema: OptimizeCodePromptInputSchema,
    outputSchema: OptimizeCodePromptOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
