'use server';
/**
 * @fileOverview Summarizes the key differences and improvements between two code outputs generated using different prompts.
 *
 * - summarizeOutputDifferences - A function that summarizes the differences between two code outputs.
 * - SummarizeOutputDifferencesInput - The input type for the summarizeOutputDifferences function.
 * - SummarizeOutputDifferencesOutput - The return type for the summarizeOutputDifferences function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const SummarizeOutputDifferencesInputSchema = z.object({
  originalOutput: z
    .string()
    .describe('The output generated by the original prompt.'),
  optimizedOutput: z
    .string()
    .describe('The output generated by the optimized prompt.'),
});
export type SummarizeOutputDifferencesInput = z.infer<
  typeof SummarizeOutputDifferencesInputSchema
>;

const SummarizeOutputDifferencesOutputSchema = z.object({
  summary: z
    .string()
    .describe(
      'A summary of the key differences and improvements in the optimized output compared to the original output.'
    ),
});
export type SummarizeOutputDifferencesOutput = z.infer<
  typeof SummarizeOutputDifferencesOutputSchema
>;

export async function summarizeOutputDifferences(
  input: SummarizeOutputDifferencesInput
): Promise<SummarizeOutputDifferencesOutput> {
  return summarizeOutputDifferencesFlow(input);
}

const prompt = ai.definePrompt({
  name: 'summarizeOutputDifferencesPrompt',
  input: {
    schema: z.object({
      originalOutput: z
        .string()
        .describe('The output generated by the original prompt.'),
      optimizedOutput: z
        .string()
        .describe('The output generated by the optimized prompt.'),
    }),
  },
  output: {
    schema: z.object({
      summary: z
        .string()
        .describe(
          'A summary of the key differences and improvements in the optimized output compared to the original output.'
        ),
    }),
  },
  prompt: `You are an AI expert in code quality and output comparison.

You are given two code outputs, one generated by an original prompt and one generated by an optimized prompt. Your task is to summarize the key differences and improvements in the optimized output compared to the original output.

Original Output:
{{originalOutput}}

Optimized Output:
{{optimizedOutput}}

Summary:`,
});

const summarizeOutputDifferencesFlow = ai.defineFlow<
  typeof SummarizeOutputDifferencesInputSchema,
  typeof SummarizeOutputDifferencesOutputSchema
>({
  name: 'summarizeOutputDifferencesFlow',
  inputSchema: SummarizeOutputDifferencesInputSchema,
  outputSchema: SummarizeOutputDifferencesOutputSchema,
},
async input => {
  const {output} = await prompt(input);
  return output!;
});
